/**
 * Metadata completa de los 66 libros de la Biblia
 */
export const booksMetadata = [
  // ==================== ANTIGUO TESTAMENTO ====================

  // PENTATEUCO (5 libros)
  {
    testament: 'OLD',
    category: 'Pentateuco',
    name: 'Génesis',
    slug: 'genesis',
    order: 1,
    totalChapters: 50,
    isAvailableInPath: true, // Disponible en MVP
  },
  {
    testament: 'OLD',
    category: 'Pentateuco',
    name: 'Éxodo',
    slug: 'exodo',
    order: 2,
    totalChapters: 40,
    isAvailableInPath: false,
  },
  {
    testament: 'OLD',
    category: 'Pentateuco',
    name: 'Levítico',
    slug: 'levitico',
    order: 3,
    totalChapters: 27,
    isAvailableInPath: false,
  },
  {
    testament: 'OLD',
    category: 'Pentateuco',
    name: 'Números',
    slug: 'numeros',
    order: 4,
    totalChapters: 36,
    isAvailableInPath: false,
  },
  {
    testament: 'OLD',
    category: 'Pentateuco',
    name: 'Deuteronomio',
    slug: 'deuteronomio',
    order: 5,
    totalChapters: 34,
    isAvailableInPath: false,
  },

  // HISTÓRICOS (12 libros)
  {
    testament: 'OLD',
    category: 'Históricos',
    name: 'Josué',
    slug: 'josue',
    order: 6,
    totalChapters: 24,
    isAvailableInPath: false,
  },
  {
    testament: 'OLD',
    category: 'Históricos',
    name: 'Jueces',
    slug: 'jueces',
    order: 7,
    totalChapters: 21,
    isAvailableInPath: false,
  },
  {
    testament: 'OLD',
    category: 'Históricos',
    name: 'Rut',
    slug: 'rut',
    order: 8,
    totalChapters: 4,
    isAvailableInPath: false,
  },
  {
    testament: 'OLD',
    category: 'Históricos',
    name: '1 Samuel',
    slug: '1-samuel',
    order: 9,
    totalChapters: 31,
    isAvailableInPath: false,
  },
  {
    testament: 'OLD',
    category: 'Históricos',
    name: '2 Samuel',
    slug: '2-samuel',
    order: 10,
    totalChapters: 24,
    isAvailableInPath: false,
  },
  {
    testament: 'OLD',
    category: 'Históricos',
    name: '1 Reyes',
    slug: '1-reyes',
    order: 11,
    totalChapters: 22,
    isAvailableInPath: false,
  },
  {
    testament: 'OLD',
    category: 'Históricos',
    name: '2 Reyes',
    slug: '2-reyes',
    order: 12,
    totalChapters: 25,
    isAvailableInPath: false,
  },
  {
    testament: 'OLD',
    category: 'Históricos',
    name: '1 Crónicas',
    slug: '1-cronicas',
    order: 13,
    totalChapters: 29,
    isAvailableInPath: false,
  },
  {
    testament: 'OLD',
    category: 'Históricos',
    name: '2 Crónicas',
    slug: '2-cronicas',
    order: 14,
    totalChapters: 36,
    isAvailableInPath: false,
  },
  {
    testament: 'OLD',
    category: 'Históricos',
    name: 'Esdras',
    slug: 'esdras',
    order: 15,
    totalChapters: 10,
    isAvailableInPath: false,
  },
  {
    testament: 'OLD',
    category: 'Históricos',
    name: 'Nehemías',
    slug: 'nehemias',
    order: 16,
    totalChapters: 13,
    isAvailableInPath: false,
  },
  {
    testament: 'OLD',
    category: 'Históricos',
    name: 'Ester',
    slug: 'ester',
    order: 17,
    totalChapters: 10,
    isAvailableInPath: false,
  },

  // POÉTICOS (5 libros)
  {
    testament: 'OLD',
    category: 'Poéticos',
    name: 'Job',
    slug: 'job',
    order: 18,
    totalChapters: 42,
    isAvailableInPath: false,
  },
  {
    testament: 'OLD',
    category: 'Poéticos',
    name: 'Salmos',
    slug: 'salmos',
    order: 19,
    totalChapters: 150,
    isAvailableInPath: false,
  },
  {
    testament: 'OLD',
    category: 'Poéticos',
    name: 'Proverbios',
    slug: 'proverbios',
    order: 20,
    totalChapters: 31,
    isAvailableInPath: false,
  },
  {
    testament: 'OLD',
    category: 'Poéticos',
    name: 'Eclesiastés',
    slug: 'eclesiastes',
    order: 21,
    totalChapters: 12,
    isAvailableInPath: false,
  },
  {
    testament: 'OLD',
    category: 'Poéticos',
    name: 'Cantares',
    slug: 'cantares',
    order: 22,
    totalChapters: 8,
    isAvailableInPath: false,
  },

  // PROFETAS MAYORES (5 libros)
  {
    testament: 'OLD',
    category: 'Profetas Mayores',
    name: 'Isaías',
    slug: 'isaias',
    order: 23,
    totalChapters: 66,
    isAvailableInPath: false,
  },
  {
    testament: 'OLD',
    category: 'Profetas Mayores',
    name: 'Jeremías',
    slug: 'jeremias',
    order: 24,
    totalChapters: 52,
    isAvailableInPath: false,
  },
  {
    testament: 'OLD',
    category: 'Profetas Mayores',
    name: 'Lamentaciones',
    slug: 'lamentaciones',
    order: 25,
    totalChapters: 5,
    isAvailableInPath: false,
  },
  {
    testament: 'OLD',
    category: 'Profetas Mayores',
    name: 'Ezequiel',
    slug: 'ezequiel',
    order: 26,
    totalChapters: 48,
    isAvailableInPath: false,
  },
  {
    testament: 'OLD',
    category: 'Profetas Mayores',
    name: 'Daniel',
    slug: 'daniel',
    order: 27,
    totalChapters: 12,
    isAvailableInPath: false,
  },

  // PROFETAS MENORES (12 libros)
  {
    testament: 'OLD',
    category: 'Profetas Menores',
    name: 'Oseas',
    slug: 'oseas',
    order: 28,
    totalChapters: 14,
    isAvailableInPath: false,
  },
  {
    testament: 'OLD',
    category: 'Profetas Menores',
    name: 'Joel',
    slug: 'joel',
    order: 29,
    totalChapters: 3,
    isAvailableInPath: false,
  },
  {
    testament: 'OLD',
    category: 'Profetas Menores',
    name: 'Amós',
    slug: 'amos',
    order: 30,
    totalChapters: 9,
    isAvailableInPath: false,
  },
  {
    testament: 'OLD',
    category: 'Profetas Menores',
    name: 'Abdías',
    slug: 'abdias',
    order: 31,
    totalChapters: 1,
    isAvailableInPath: false,
  },
  {
    testament: 'OLD',
    category: 'Profetas Menores',
    name: 'Jonás',
    slug: 'jonas',
    order: 32,
    totalChapters: 4,
    isAvailableInPath: false,
  },
  {
    testament: 'OLD',
    category: 'Profetas Menores',
    name: 'Miqueas',
    slug: 'miqueas',
    order: 33,
    totalChapters: 7,
    isAvailableInPath: false,
  },
  {
    testament: 'OLD',
    category: 'Profetas Menores',
    name: 'Nahúm',
    slug: 'nahum',
    order: 34,
    totalChapters: 3,
    isAvailableInPath: false,
  },
  {
    testament: 'OLD',
    category: 'Profetas Menores',
    name: 'Habacuc',
    slug: 'habacuc',
    order: 35,
    totalChapters: 3,
    isAvailableInPath: false,
  },
  {
    testament: 'OLD',
    category: 'Profetas Menores',
    name: 'Sofonías',
    slug: 'sofonias',
    order: 36,
    totalChapters: 3,
    isAvailableInPath: false,
  },
  {
    testament: 'OLD',
    category: 'Profetas Menores',
    name: 'Hageo',
    slug: 'hageo',
    order: 37,
    totalChapters: 2,
    isAvailableInPath: false,
  },
  {
    testament: 'OLD',
    category: 'Profetas Menores',
    name: 'Zacarías',
    slug: 'zacarias',
    order: 38,
    totalChapters: 14,
    isAvailableInPath: false,
  },
  {
    testament: 'OLD',
    category: 'Profetas Menores',
    name: 'Malaquías',
    slug: 'malaquias',
    order: 39,
    totalChapters: 4,
    isAvailableInPath: false,
  },

  // ==================== NUEVO TESTAMENTO ====================

  // EVANGELIOS (4 libros)
  {
    testament: 'NEW',
    category: 'Evangelios',
    name: 'Mateo',
    slug: 'mateo',
    order: 40,
    totalChapters: 28,
    isAvailableInPath: false,
  },
  {
    testament: 'NEW',
    category: 'Evangelios',
    name: 'Marcos',
    slug: 'marcos',
    order: 41,
    totalChapters: 16,
    isAvailableInPath: false,
  },
  {
    testament: 'NEW',
    category: 'Evangelios',
    name: 'Lucas',
    slug: 'lucas',
    order: 42,
    totalChapters: 24,
    isAvailableInPath: false,
  },
  {
    testament: 'NEW',
    category: 'Evangelios',
    name: 'Juan',
    slug: 'juan',
    order: 43,
    totalChapters: 21,
    isAvailableInPath: true, // Disponible en MVP
  },

  // HISTÓRICO (1 libro)
  {
    testament: 'NEW',
    category: 'Histórico',
    name: 'Hechos',
    slug: 'hechos',
    order: 44,
    totalChapters: 28,
    isAvailableInPath: false,
  },

  // EPÍSTOLAS PAULINAS (13 libros)
  {
    testament: 'NEW',
    category: 'Epístolas Paulinas',
    name: 'Romanos',
    slug: 'romanos',
    order: 45,
    totalChapters: 16,
    isAvailableInPath: false,
  },
  {
    testament: 'NEW',
    category: 'Epístolas Paulinas',
    name: '1 Corintios',
    slug: '1-corintios',
    order: 46,
    totalChapters: 16,
    isAvailableInPath: false,
  },
  {
    testament: 'NEW',
    category: 'Epístolas Paulinas',
    name: '2 Corintios',
    slug: '2-corintios',
    order: 47,
    totalChapters: 13,
    isAvailableInPath: false,
  },
  {
    testament: 'NEW',
    category: 'Epístolas Paulinas',
    name: 'Gálatas',
    slug: 'galatas',
    order: 48,
    totalChapters: 6,
    isAvailableInPath: false,
  },
  {
    testament: 'NEW',
    category: 'Epístolas Paulinas',
    name: 'Efesios',
    slug: 'efesios',
    order: 49,
    totalChapters: 6,
    isAvailableInPath: false,
  },
  {
    testament: 'NEW',
    category: 'Epístolas Paulinas',
    name: 'Filipenses',
    slug: 'filipenses',
    order: 50,
    totalChapters: 4,
    isAvailableInPath: false,
  },
  {
    testament: 'NEW',
    category: 'Epístolas Paulinas',
    name: 'Colosenses',
    slug: 'colosenses',
    order: 51,
    totalChapters: 4,
    isAvailableInPath: false,
  },
  {
    testament: 'NEW',
    category: 'Epístolas Paulinas',
    name: '1 Tesalonicenses',
    slug: '1-tesalonicenses',
    order: 52,
    totalChapters: 5,
    isAvailableInPath: false,
  },
  {
    testament: 'NEW',
    category: 'Epístolas Paulinas',
    name: '2 Tesalonicenses',
    slug: '2-tesalonicenses',
    order: 53,
    totalChapters: 3,
    isAvailableInPath: false,
  },
  {
    testament: 'NEW',
    category: 'Epístolas Paulinas',
    name: '1 Timoteo',
    slug: '1-timoteo',
    order: 54,
    totalChapters: 6,
    isAvailableInPath: false,
  },
  {
    testament: 'NEW',
    category: 'Epístolas Paulinas',
    name: '2 Timoteo',
    slug: '2-timoteo',
    order: 55,
    totalChapters: 4,
    isAvailableInPath: false,
  },
  {
    testament: 'NEW',
    category: 'Epístolas Paulinas',
    name: 'Tito',
    slug: 'tito',
    order: 56,
    totalChapters: 3,
    isAvailableInPath: false,
  },
  {
    testament: 'NEW',
    category: 'Epístolas Paulinas',
    name: 'Filemón',
    slug: 'filemon',
    order: 57,
    totalChapters: 1,
    isAvailableInPath: false,
  },

  // EPÍSTOLAS GENERALES (8 libros)
  {
    testament: 'NEW',
    category: 'Epístolas Generales',
    name: 'Hebreos',
    slug: 'hebreos',
    order: 58,
    totalChapters: 13,
    isAvailableInPath: false,
  },
  {
    testament: 'NEW',
    category: 'Epístolas Generales',
    name: 'Santiago',
    slug: 'santiago',
    order: 59,
    totalChapters: 5,
    isAvailableInPath: false,
  },
  {
    testament: 'NEW',
    category: 'Epístolas Generales',
    name: '1 Pedro',
    slug: '1-pedro',
    order: 60,
    totalChapters: 5,
    isAvailableInPath: false,
  },
  {
    testament: 'NEW',
    category: 'Epístolas Generales',
    name: '2 Pedro',
    slug: '2-pedro',
    order: 61,
    totalChapters: 3,
    isAvailableInPath: false,
  },
  {
    testament: 'NEW',
    category: 'Epístolas Generales',
    name: '1 Juan',
    slug: '1-juan',
    order: 62,
    totalChapters: 5,
    isAvailableInPath: false,
  },
  {
    testament: 'NEW',
    category: 'Epístolas Generales',
    name: '2 Juan',
    slug: '2-juan',
    order: 63,
    totalChapters: 1,
    isAvailableInPath: false,
  },
  {
    testament: 'NEW',
    category: 'Epístolas Generales',
    name: '3 Juan',
    slug: '3-juan',
    order: 64,
    totalChapters: 1,
    isAvailableInPath: false,
  },
  {
    testament: 'NEW',
    category: 'Epístolas Generales',
    name: 'Judas',
    slug: 'judas',
    order: 65,
    totalChapters: 1,
    isAvailableInPath: false,
  },

  // PROFÉTICO (1 libro)
  {
    testament: 'NEW',
    category: 'Profético',
    name: 'Apocalipsis',
    slug: 'apocalipsis',
    order: 66,
    totalChapters: 22,
    isAvailableInPath: false,
  },
];
